### ISSUE TITLE
[Discussion] Add clippy and rustfmt to travis

### ISSUE THREAD

**Issue by Drakulix** [vberger/smithay#10]
I don't know, how you normally manage this in your projects, but I have adapted to provide a rustfmt configuration for all my projects to get a mostly consistent style, which is also very useful for contributers and I found clippy's default lint to be quite helpful to avoid some rather common error.

Any thoughts?

**Comment by vberger** [comment]
I'm all for it, do you have a working configuration we could add here?

**Comment by Drakulix** [comment]
you can also use no configuration for default values, my personal currently is: https://github.com/Drakulix/fireplace/blob/master/.rustfmt.toml

Feel free to modify as you wish.

**Comment by vberger** [comment]
Ah, I was thinking about a way to integrate them in the travis build, rather than rustfmt config 😅

**Comment by Drakulix** [comment]
Sorry my fault.
I currently don't have an easy .travis.yml that does add, because I am using [vagga](https://github.com/tailhook/vagga) for most of my travis builds.

But configuration for both is very easy:

- rustfmt has an example in its README: https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server
- for clippy the easiest way is to add `cargo install -f clippy` to your setup and just change `cargo build` into `cargo clippy` for your nightly builds.

**Comment by vberger** [comment]
Okay, thanks for the pointers, I'll look into that!
