### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Drakulix** [vberger/smithay#13]
We should probably decide on a license.
I am in favor of something permissive.

**Comment by vberger** [comment]
Indeed. My other projects are all MIT, but to be honest I don't have any strong feeling.

For wayland-client and wayland-server, I mostly stuck with MIT because it's the license of the C libraries.

I see many rust projects are MIT+Apache2.0. What do you think about that?

**Comment by Drakulix** [comment]
Both combinations are fine for me. `servo` started with this MIT + Apache2 thing, that's why many crates are following, but I honest don't care very much. I am using only MIT for most of my project, but feel free to do what you want out of these possibilities.

**Comment by vberger** [comment]
Well. We'll go with MIT, and if any issues with it are brought up, we'll discuss them then.
